package Views;

import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author mitchellgriffith
 */
public class MyFrame extends javax.swing.JFrame {
  
  public JTextField getLogin(){ return this.loginTextField; }
  public JTextField getCurrentPass(){ return this.currentPassTextField; }
  public JTextField getNewPass(){ return this.newPassTextField; }
  public JTextArea getTextArea(){ return this.textArea; }
  public JButton getChangePass(){ return this.changePassButton; }
  public JButton getDumpData(){ return this.dumpDataButton; }
  

  /**
   * Creates new form MyFrame
   */
  public MyFrame() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    loginLabel = new javax.swing.JLabel();
    loginTextField = new javax.swing.JTextField();
    currentPassLabel = new javax.swing.JLabel();
    currentPassTextField = new javax.swing.JTextField();
    newPassLabel = new javax.swing.JLabel();
    newPassTextField = new javax.swing.JTextField();
    changePassButton = new javax.swing.JButton();
    dumpDataButton = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    textArea = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    loginLabel.setText("Login");

    currentPassLabel.setText("Current Password");

    currentPassTextField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        currentPassTextFieldActionPerformed(evt);
      }
    });

    newPassLabel.setText("New Password");

    changePassButton.setText("Change Password");

    dumpDataButton.setText("Dump Data");

    textArea.setColumns(20);
    textArea.setRows(5);
    jScrollPane1.setViewportView(textArea);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(125, 125, 125)
        .addComponent(changePassButton)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
        .addComponent(dumpDataButton)
        .addGap(153, 153, 153))
      .addGroup(layout.createSequentialGroup()
        .addGap(69, 69, 69)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(currentPassLabel)
              .addComponent(newPassLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(currentPassTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
              .addComponent(loginTextField)
              .addComponent(newPassTextField))
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(loginLabel)
          .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(currentPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(currentPassLabel))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(newPassLabel)
          .addComponent(newPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(changePassButton)
          .addComponent(dumpDataButton))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(22, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void currentPassTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentPassTextFieldActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_currentPassTextFieldActionPerformed

  /**
   * @param args the command line arguments
   */


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton changePassButton;
  private javax.swing.JLabel currentPassLabel;
  private javax.swing.JTextField currentPassTextField;
  private javax.swing.JButton dumpDataButton;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel loginLabel;
  private javax.swing.JTextField loginTextField;
  private javax.swing.JLabel newPassLabel;
  private javax.swing.JTextField newPassTextField;
  private javax.swing.JTextArea textArea;
  // End of variables declaration//GEN-END:variables
}
